"""Bot strategy — executes LLM-generated Python code in a WASM sandbox."""

from __future__ import annotations

from typing import Any

import structlog

from nexow.strategies.base import BaseStrategy, Signal, SignalType
from nexow.broker.models import Candle

logger = structlog.get_logger(__name__)


class BotStrategy(BaseStrategy):
    """
    Rule-based trading bot powered by WASM-sandboxed Python code.

    The bot's config contains `strategy_code` — a Python evaluate() function
    generated by the Bot Factory LLM. At runtime, this code is sent to the
    Pyodide WASM sandbox sidecar along with candle data.

    Tracks the last candle time so evaluations only fire once per new candle.
    """

    _last_candle_times: dict[str, float] = {}

    def __init__(self, strategy_id: str, config: dict[str, Any]) -> None:
        super().__init__(strategy_id, config)
        self.strategy_code: str = config.get("strategy_code", "")

    async def evaluate(self, candles: list[Candle], current_price: float) -> Signal:
        instrument = candles[0].instrument if candles else "UNKNOWN"

        if not self.strategy_code:
            return Signal(type=SignalType.HOLD, instrument=instrument, reason="No strategy code configured")

        if len(candles) < 2:
            return Signal(type=SignalType.HOLD, instrument=instrument, reason="Not enough candle data")

        # Deduplicate: only evaluate once per new candle
        cache_key = f"{self.strategy_id}:{instrument}"
        ref_time = candles[-1].time.timestamp()
        prev_time = self._last_candle_times.get(cache_key, 0)

        if ref_time <= prev_time:
            return Signal(type=SignalType.HOLD, instrument=instrument, reason="Waiting for new candle")

        self._last_candle_times[cache_key] = ref_time

        action = await self._execute(candles, current_price)

        signal_map = {
            "buy": SignalType.BUY,
            "sell": SignalType.SELL,
            "close": SignalType.CLOSE,
            "hold": SignalType.HOLD,
        }

        signal_type = signal_map.get(action, SignalType.HOLD)

        exit_config = self.config.get("exit", {})
        sl_pct = exit_config.get("stop_loss_pct")
        tp_pct = exit_config.get("take_profit_pct")

        return Signal(
            type=signal_type,
            instrument=instrument,
            confidence=0.8 if signal_type != SignalType.HOLD else 0.0,
            stop_loss_pct=sl_pct if signal_type in (SignalType.BUY, SignalType.SELL) else None,
            take_profit_pct=tp_pct if signal_type in (SignalType.BUY, SignalType.SELL) else None,
            reason=f"Strategy → {action}",
        )

    async def _execute(self, candles: list[Candle], current_price: float) -> str:
        """Execute strategy code in the WASM sandbox."""
        from nexow.strategies.wasm_client import execute_strategy
        from nexow.db.client import SupabaseClient

        candle_dicts = [
            {
                "open": c.open,
                "high": c.high,
                "low": c.low,
                "close": c.close,
                "volume": c.volume,
                "time": c.time.isoformat(),
            }
            for c in candles
        ]

        try:
            db = SupabaseClient()
            open_trades = len(db.get_open_trades(self.strategy_id))
        except Exception:
            open_trades = 0

        return await execute_strategy(
            code=self.strategy_code,
            candles=candle_dicts,
            current_price=current_price,
            open_trade_count=open_trades,
        )
